### ISSUE TITLE
Bug: paragraphs not always split between pages

### ISSUE THREAD

**Issue by JC-NR** [evnbr/bindery#66] opened 2019-12-04 11:42 UTC
First of all, a big bravo for the work done.
Easy to use and yet powerful.

But sometimes I have a problem with my paragraphs: they don't always split. See the following example, and the associated code.

![image](https://user-images.githubusercontent.com/38077758/70138907-98550880-1691-11ea-8a74-a417ba957ae1.png)

```js
const {makeBook, PageBreak, RunningHeader, Layout, Paper, Marks, Split} = Bindery;
makeBook({
  content: '#content',
  printSetup: {
    layout: Layout.PAGES,
    paper: Paper.AUTO,
    marks: Marks.NONE
  },
  pageSetup: {
    size: { width: '148mm', height: '209.5mm' },
    margin: {
      top: '0.4in',
      bottom: '0.3in',
      inner: '0.3in',
      outer: '0.3in',
    },
  },
  rules: [
    Split({
      selector: 'p',
      toNext: 'continues',
      fromPrevious: 'continued',
    }),
    PageBreak({
      selector: 'section',
      position: 'before',
      continue: 'right'
    }),
    RunningHeader({
      render: (page) => {
        if (page.isEmpty || page.number <= 1) return '';
        if (page.isLeft) return `${page.number} · Borden `;
        else if (page.isRight) {
          let section = page.heading.h1 || '';
          if (section !== '') return `${section} · ${page.number}`;
          else return `${page.number}`;
        }
      },
    }),
  ]
});
```

**Comment by evnbr** [comment] 2020-02-24 00:13
hi @JC-NR , I imagine you intend the bottom of Page 8 to be filled with content? mind sharing a working example I can run, somewhere like Codepen or JSFiddle?

**Comment by evnbr** [comment] 2021-01-11 18:40
Closing as I'm unable to reproduce the issue, feel free to reopen if you have a working example

**Closed by evnbr** 2021-01-11 18:40 UTC
